language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
    - sudo apt-get install gdb

install: ./travis-init.sh
  
script:
    - phpunit --coverage-text
